export default {
  '__comp---theme-debug-config-23-a-2ff': [() => import(/* webpackChunkName: '__comp---theme-debug-config-23-a-2ff' */ '@theme/DebugConfig'), '@theme/DebugConfig', require.resolveWeak('@theme/DebugConfig')],
  '__comp---theme-debug-contentba-8-ce7': [() => import(/* webpackChunkName: '__comp---theme-debug-contentba-8-ce7' */ '@theme/DebugContent'), '@theme/DebugContent', require.resolveWeak('@theme/DebugContent')],
  '__comp---theme-debug-global-dataede-0fa': [() => import(/* webpackChunkName: '__comp---theme-debug-global-dataede-0fa' */ '@theme/DebugGlobalData'), '@theme/DebugGlobalData', require.resolveWeak('@theme/DebugGlobalData')],
  '__comp---theme-debug-registry-679-501': [() => import(/* webpackChunkName: '__comp---theme-debug-registry-679-501' */ '@theme/DebugRegistry'), '@theme/DebugRegistry', require.resolveWeak('@theme/DebugRegistry')],
  '__comp---theme-debug-routes-946-699': [() => import(/* webpackChunkName: '__comp---theme-debug-routes-946-699' */ '@theme/DebugRoutes'), '@theme/DebugRoutes', require.resolveWeak('@theme/DebugRoutes')],
  '__comp---theme-debug-site-metadata-68-e-3d4': [() => import(/* webpackChunkName: '__comp---theme-debug-site-metadata-68-e-3d4' */ '@theme/DebugSiteMetadata'), '@theme/DebugSiteMetadata', require.resolveWeak('@theme/DebugSiteMetadata')],
  '__comp---theme-doc-item-178-a40': [() => import(/* webpackChunkName: '__comp---theme-doc-item-178-a40' */ '@theme/DocItem'), '@theme/DocItem', require.resolveWeak('@theme/DocItem')],
  '__comp---theme-doc-page-1-be-9be': [() => import(/* webpackChunkName: '__comp---theme-doc-page-1-be-9be' */ '@theme/DocPage'), '@theme/DocPage', require.resolveWeak('@theme/DocPage')],
  'allContent---docusaurus-debug-content-246-9aa': [() => import(/* webpackChunkName: 'allContent---docusaurus-debug-content-246-9aa' */ '~debug/default/docusaurus-debug-all-content-673.json'), '~debug/default/docusaurus-debug-all-content-673.json', require.resolveWeak('~debug/default/docusaurus-debug-all-content-673.json')],
  'content---c-37-d02': [() => import(/* webpackChunkName: 'content---c-37-d02' */ '@site/docs/index.md'), '@site/docs/index.md', require.resolveWeak('@site/docs/index.md')],
  'plugin---61-c-ed7': [() => import(/* webpackChunkName: 'plugin---61-c-ed7' */ '/home/break_happy/project/stream8/packages/pkg1/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json'), '/home/break_happy/project/stream8/packages/pkg1/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json', require.resolveWeak('/home/break_happy/project/stream8/packages/pkg1/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json')],
  'plugin---docusaurus-debugaba-c08': [() => import(/* webpackChunkName: 'plugin---docusaurus-debugaba-c08' */ '/home/break_happy/project/stream8/packages/pkg1/.docusaurus/docusaurus-plugin-debug/default/plugin-route-context-module-100.json'), '/home/break_happy/project/stream8/packages/pkg1/.docusaurus/docusaurus-plugin-debug/default/plugin-route-context-module-100.json', require.resolveWeak('/home/break_happy/project/stream8/packages/pkg1/.docusaurus/docusaurus-plugin-debug/default/plugin-route-context-module-100.json')],
  'versionMetadata---935-fcf': [() => import(/* webpackChunkName: 'versionMetadata---935-fcf' */ '~docs/default/version-current-metadata-prop-751.json'), '~docs/default/version-current-metadata-prop-751.json', require.resolveWeak('~docs/default/version-current-metadata-prop-751.json')],};
