import PlayerService from '../player';
declare class HttpFlvStreamLoader {
    private _requestAbort;
    private _abortController;
    private _abortController2;
    private _requestAbort2;
    private _chunks2;
    private playerService;
    url: string;
    private downLoadConfig;
    private streamParser;
    maxHeartTimes: number;
    hertTime: number;
    constructor();
    initAudioPlayer(): void;
    static isSupported(): boolean;
    get requestAbort(): boolean;
    set requestAbort(value: boolean);
    get abortController(): AbortController;
    init(playerService: PlayerService, url: string): void;
    open(): void;
    abort(): void;
    destroy(): void;
    fetchStream(): Promise<void>;
    abortFetch(): void;
    downLoadBlob(blob: Blob): void;
    downLoad(): Promise<void>;
    abortDownLoad(): void;
    processStream(reader: ReadableStreamDefaultReader): Promise<void>;
    processFlvChunk(chunk: Uint8Array): void;
}
export default HttpFlvStreamLoader;
